# Generated by Django 4.1.6 on 2023-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
